### ISSUE TITLE
 map_container not found

### ISSUE THREAD

**Issue by aritrabasu104** [SBejga/ionic2-map-leaflet#3]
I am getting an issue that says map_container not found _initContainer...

**Comment by SBejga** [comment]
Mh, map_container should not be used. 

In my example there is `.map-container`. But you should use `#map` inside it.

**map.html**
```
<div class="map-container">
    <div id="map" style="width: 100%; height: 100%">
    </div>
</div>
```

check if the Id matches with your map init in https://github.com/SBejga/ionic2-map-leaflet/blob/master/src/pages/map/map.ts#L34 the string there is the id of the html element.
